builders:
  typesgenerator:
    import: "package:typings/tool/build.dart"
    builder_factories: [
        "typingsBuilder"
    ]
    build_extensions: {".dart": [".info.dart"]}
    #auto_apply: dependents
    auto_apply: none
    build_to: source
  coregenerator:
    import: "package:typings/tool/build.dart"
    builder_factories: [
        "typingsBuilder"
    ]
    build_extensions: {".dart": [".info.dart"]}
    #auto_apply: dependents
    auto_apply: none
    build_to: source
    runs_before: [
        "typings|typesgenerator",
    ]

targets:
  $default:
    builders:
      typings|coregenerator:
        enabled: false
        generate_for:
          - lib/core.dart
      typings|typesgenerator:
        enabled: false
        generate_for:
          - lib/d/*.dart
      build_web_compilers|entrypoint:
        enabled: true
        options:
          compiler: dart2js
          dart2js_args:
            #- --fast-startup
            - -O1
            - --no-minify
            #- --trust-primitives
            #- --omit-implicit-checks
            #- --dump-info
        release_options:
          dart2js_args:
            - --fast-startup
            - -O4
            - --minify
            - --trust-primitives
            - --omit-implicit-checks
            #- --dump-info

