name: typings
description: Use NPM packages in your projects through TypeScript interop
version: 0.0.1
repository: https://github.com/jodinathan/typings/typings

funding: https://www.paypal.com/donate?hosted_button_id=YNCG33GLM3494

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

# Add regular dependencies here.
#dependencies:
  

dev_dependencies:
  analyzer: ^5.10.0
  build_web_compilers: ^4.0.0
  build: ^2.3.1
  build_runner: ^2.4.1
  js: ^0.6.7
  lints: ^2.0.0
  source_gen: ^1.2.7
  test: ^1.21.0
  ts2dart:
    path: ../ts2dart

dependency_overrides:
  code_builder:
   path: ../code_builder
